### ISSUE TITLE
Rendering DDL script for Oracle

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SqlRender#122]
I seem to be facing a problem when attempting to render & translate the following DDL SQL code to Oracle:

```
IF OBJECT_ID('@results_schema.test_table', 'U') IS NULL
CREATE TABLE @results_schema.test_table
(
	analysis_id INT NOT NULL, 
	person_id BIGINT NOT NULL
);
```

Here is what I expected from SqlRender:

```
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ohdsi.test_table
 (analysis_id NUMBER(10) NOT NULL, 
	person_id NUMBER(19) NOT NULL
)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
```

However, here is the SQL I receive:
```
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ohdsi.test_table
 (analysis_id INT NOT NULL, 
	person_id BIGINT NOT NULL
)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;

```

Note the difference in the data types for the column declarations - after translating to Oracle, it has not replaced the INT/BIGINT types. Digging into this, I'm finding two things:

1. We do not have a replacement pattern for Oracle that would translate INT to NUMBER(10). I'm happy to add this via a pull request.
2. The replacement pattern for BIGINT (https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv#L89) does not appear to fire for some reason? I tried changing the DDL to remove the "NOT NULL" portion of the column declaration but got the same results.

Any ideas on item 2 above? Just let me know if you'd like me to add the other replacement pattern. Thanks!

**Comment by schuemie** [comment]
I think I've fixed item 2 [in this commit](https://github.com/OHDSI/SqlRender/commit/feaff868f38145c1a8e6d0d52e2c508fd35ec447). In short, even though search patterns can include things that are quoted, the quotes need to be part of the pattern. Otherwise, things in quotes are ignored. In this case, the first rule introduced quote around the CREATE TABLE SQL statement, preventing subsequent rules from firing on that SQL. I changed the order of the rules to prevent that.

INT is a valid data type in Oracle, so I'm not sure we need to translate it to NUMBER. Can you think of a reason why we should translate it?
