### ISSUE TITLE
translateSingleStatement fails for translation cases resulting in multiple statements

### ISSUE THREAD

**Issue by pavgra** [OHDSI/SqlRender#158]
Execution of
```
SqlRender::translateSingleStatement("SELECT * INTO #temp FROM dual;", targetDialect = "postgresql")
```

fails with:
```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.RuntimeException: SQL contains more than one statement: CREATE TEMP TABLE temp 
AS
SELECT
* 
FROM
dual;
ANALYZE temp ;
```

**Comment by chrisknoll** [comment]
@pavgra, is the error, in your opinion, the 'ANALYZE temp' is not a valid statement in oracle, or that the SELECT..INTO results in multiple statements?

I'm thinking in this case: this is an insert INTO, not a select and in this specific case, the insert into a newly created table creates a temp table which is 'analyized' is going to result in mulitiple statements, so we should not expect `translateSingleStatement` to resolve into a single statement, and we should be split + `batchUpdate()` this statement.

the translateSingleStatement was geared towards those statements that _must_ result in a single statement that you can use `executeQuery()` to invoke, because you are expecting the only result to be returned is a `ResultSet`.

So, I'm not exactly what the course of action you would like to take here. Normally in the bug requests I submit there's an 'expected' and 'actual' result.  What's the 'actual' result you were expecting?

**Comment by pavgra** [comment]
> we should not expect `translateSingleStatement` to resolve into a single statement

@chrisknoll, I believe it's OK to expect from a function named "translate single statement" to work without exceptions when I pass a *single* statement into it. I, a developer, shouldn't know the differences between outputs for e.g. PDW vs PostgreSQL - otherwise, what's the reason for SqlRender? So, if the function works for e.g. PDW, it should work for PostgreSQL. Or shouldn't work for both.

**Comment by schuemie** [comment]
I think the name was maybe not the best choice. Basically, you can use this function when you *query* the database, so when you expect results (and by definition you'll have only one SQL statement both before and after translation. Whenever you want to execute (ie. update) statements, the expected behavior should be to call `translateSql` then `splitSql`. 

I could add a function that combines `translateSql` and `splitSql` into one, so similar to `translateSingleStatement` but the output would be an array of strings instead of a single string. But I'm really starting to wonder whether we need all this in SqlRender, or whether you want some wrapper functions in WebApi similar to `executeSql` and `querySql` in DatabaseConnector.

**Comment by pavgra** [comment]
@schuemie , I solved the issue inside WebAPI (https://github.com/OHDSI/WebAPI/pull/840/files) but anyway, the function's naming combined with its behavior is confusing as for me

**Comment by schuemie** [comment]
I agree. Shall I deprecate the function in SqlRender?

**Comment by chrisknoll** [comment]
> @chrisknoll, I believe it's OK to expect from a function named "translate single statement" to work without exceptions when I pass a _single_ statement into it. I, a developer, shouldn't know the differences between outputs for e.g. PDW vs PostgreSQL - otherwise, what's the reason for SqlRender? So, if the function works for e.g. PDW, it should work for PostgreSQL. Or shouldn't work for both.

@pavgra , if you would kindly re-read what was discussed about the need for this feature:  the context was that there are times when you must expect that the translated query must result in exactly 1 statement, specifically in the case of querying from the database. If a query resulted in two statements, which one contains the result set?  So, in the case where you found the error, it was working as intended, you discovered the error, and had to adjust it to handle the case where the Insert/Update may result in multiple statements (in your case the create table, and update table statistics).  

It sounds like the solution you settled on was what the original suggestion proposed: split the sql.  You mentioned that it was going to be a large refactor, but it looks like it wasn't.

@schuemie: there still may be a use case for this function. When I'm going to execute a query and I expect just 1 statement to be executed and 1 result set to be returned, finding out that multiple statements were generated during translate would be a good fail-safe.  But this is just one opinion, and if you want to keep the API small, then the understanding that inserts/updates should always be split and query statements may need to be checked for multiple statements is what we'll have to live with.
