### ISSUE TITLE
Support for percent_rank

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#203]
@schuemie :

For the [DataQualityDashboard](https://github.com/OHDSI/DataQualityDashboard), we were considering adding some percentile based DQ checks. 

I see that we currently only have 1 percent_rank translation pattern for Redshift. Does that indicate that we've tested this function for all other dialects and they don't need any translation? Or that it has not been addressed for all the other dialects?

Tagging @vojtechhuser @clairblacketer

**Comment by vojtechhuser** [comment]
Can also explain me how this code for 25th percentile (and others) work?

Since this would also solve our problem.
https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/1815.sql

e.g., ranking all values (and counting them) and taking the middle row (or 3/4 row) and that is the 75th?

**Comment by schuemie** [comment]
I try to keep a complete list of the functions that translate well (or don't need translation) [here](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate). Percentile functions are not there, and this is because the syntax is so vastly different across platforms that translation is not possible.

The solution is to use the rather elaborate structure that @vojtechhuser  pointed to. This is explained in some detail in [the SQL and R chapter in the Book of Ohdsi](https://ohdsi.github.io/TheBookOfOhdsi/SqlAndR.html#QueryTheCdm).
