### ISSUE TITLE
Replace oracleTempSchema with a global option

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#215]
Database platforms that don't support temp tables rely on the `oracleTempSchema` argument to emulate temp tables in that schema. There are two issues with that:
1. It requires all applications using SqlRender to perpetuate the `oracleTempSchema` argument throughout the call stack.
2. The feature is now used by other platforms as well (BigQuery, Impala), so the 'Oracle' part is a misnomer.

We could replace the argument with a global option, so users on these platforms would need to issue a statement like:

```r
option("SqlRenderTempSchema" = "my_schema")
```

And all `translate` calls would simply poll this option. We could probably also throw an error or warning if on these platforms people translate SQL with temp table references without having this option set.

**Comment by alondhe** [comment]
Thanks for adding this -- I was thinking about this for Spark as well. I've been using oracleTempSchema for it since there is no concept of temp tables really.

**Comment by schuemie** [comment]
I get we could change [this](https://github.com/OHDSI/SqlRender/blob/master/R/RenderSql.R#L141) to simply read
```r
translateSql <- function(sql = "",
                         targetDialect,
                         oracleTempSchema = getOption("SqlRenderTempSchema")) {
```
That way old code would work, as well as new code where we didn't perpetuate this argument.


Somehow we'd need to make it clear to users of these platforms that they're expected to set this option. I'm not sure what the best way is to do that?

Alternatively, we could add an argument to DatabaseConnector's `createConnectionDetails` and `connect` functions? It could then be carried forward as part of the `connectionDetails` and `connection` objects.

**Comment by jreps** [comment]
+1 on setting it in the createConnectionDetails

**Comment by alondhe** [comment]
I'd prefer in the createConnectionDetails object as well. Maybe we can add a new parameter called "tempTableSchema," and then set the default value of oracleTempSchema to tempSchema?

**Comment by anthonysena** [comment]
+1 on the connection details as well. In WebAPI, we have this notion of the "temp" schema which is essentially a place to store transient data used in an analysis where a JDBC connection is severed (this is done in the pathways analysis for example). Storing this in the connection details makes this easier so that we can specify the temp schema when creating the connection and then use it through the analyses as described in this issue. Thanks!

**Comment by schuemie** [comment]
Hmmm, I'm not sure how we would get that information from the connectionDetails to SqlRender though. A typical call looks like this:
```r
connection <- connect(connectionDetails)
sql <- "SELECT * FROM #temp;"
sql <- SqlRender::translate(sql, connection@dbms)
x <- querySql(connection, sql)
```

We can store `sqlRenderTempSchema` in `connectionDetails`, which could pass it on to `connection`, but we don't want to explicitly pass it on to `translate` because that would defeat the purpose.

**Comment by alondhe** [comment]
Taking a step back, the current approach of `oracleTempSchema` in `translate()` works just fine. The only issue I see with it is just the name of the parameter being confusing for new users, as we have 3 dbms's (BigQuery, Impala, Spark) that aren't oracle and need this functionality.

I'm re-thinking my earlier stance: what are the benefits of having this construct in connectionDetails? A `connectionDetails` object is simply the items needed to make the JDBC connection. In it, we don't really care about schemas. In fact, we've already deprecated the only vestige of schema information just recently (https://github.com/OHDSI/DatabaseConnector/pull/110). Adding info about where to place temp tables would seem to be irrelevant in the context of `connectionDetails`.

Can we instead just deprecate `oracleTempSchema` in translate and add a more appropriately named parameter in its place? `sqlRenderTempSchema` is fine, but a bit redundant since the `translate()` function is part of SqlRender. `tempTableSchema`?

**Comment by SulevR** [comment]
I think that we need this change because of the other problem that @schuemie mentioned: one has to bring oracleTempSchema through the callstack. If you are not using temporary schemas, you build your package without that parameter. As soon as you want to bring in some temporary table, you have to add oracleTempSchema parameter to all parent functions (it is, to update definitions of all functions which is cumbersome). One may argue that "just in case" always add this parameter to all your function but this is not a good practice to make software.

This parameter is not directly related to creating the connection as @alondhe points out but is definitely related to the connection. Now it is the question whether connectionDetails is good enough place to store this. For me, it seems reasonable.

**Comment by schuemie** [comment]
Implemented in [this commit](https://github.com/OHDSI/SqlRender/commit/808055960810e2f5e3a89306e3f811e1a5bcba3a). Will be released shortly
