### ISSUE TITLE
Redshift IsNumeric translation issue

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/SqlRender#276]
The Regex used [here](https://github.com/OHDSI/SqlRender/blob/a3b38a9306c651b005718acf1aaaef35d7b56d50/inst/csv/replacementPatterns.csv#L379) to translate "isnumeric" into Redshift dialect sometimes throws an error like this one:

> ERROR:  Invalid digit, Value '.', Pos 1, Type: Integer 
> DETAIL:  
>   -----------------------------------------------
>   error:  Invalid digit, Value '.', Pos 1, Type: Integer 
>   code:      1207
>   context:   2.87
>   query:     101859300
>   location:  :0
>   process:   query1_63_101859300 [pid=0]
>   -----------------------------------------------

I ran into this issue when investigating why some visualizations weren't showing up on the Data Sources tab of ATLAS - I believe it's because some of the SQL queries [here](https://github.com/OHDSI/WebAPI/tree/master/src/main/resources/resources/cdmresults/sql/report) are throwing the above error when running against my Redshift DB.

In case it's helpful:

- I see a similar issue was addressed [here](https://github.com/OHDSI/SqlRender/issues/188) for Postgres.
- I was able to get [this](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/report/condition/drilldown/ageAtFirstOccurrence.sql) query to stop throwing that error by swapping out this regex check - `REGEXP_INSTR(ard1.stratum_1, '^[\-\+]?(\\d*\\.)?\\d+([Ee][\-\+]?\\d+)?$') = 1` for this one - `REGEXP_COUNT(ard1.stratum_1, '^[0-9]+$') != 0`

Let me know if I can provide further info.  Thanks for your help!

**Comment by schuemie** [comment]
Thanks! The regex seems to be fine, and appears to be correctly testing whether the value is *numeric*, which can include values such as `1.1.`, `1e10`, etc. However, in the query the test is used to see whether the value can be joined to the `concept_id` field, which I think is an integer. So just because `stratum_1` is found to be a numeric doesn't mean it is an integer, which I think is causing the error. 

I've created an [issue in the WebApi repo](https://github.com/OHDSI/WebAPI/issues/2030). Let's see what they say about this.

**Comment by katy-sadowski** [comment]
Aha, you are right!  Thanks for filing that issue; I'll follow along there :)
