### ISSUE TITLE
Throw error if single equals-sign in condition

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/SqlRender#30]
Trying to do the following:

--{ runCostAnalaysis } ? { 
--Analysis SQL
-- This block has inner If-Else statements
-- { 1502 in (@list_of_analysis_ids) } ? {
-- Analysis 1502 work
--} -- This ends analysis 1502 IF
--} -- this ends runCostAnalysis IF

Simple R case:

``` R
sql <- "{@y = 2} ? { SELECT * FROM table {@x == 1} ? {WHERE id = 1}; } : { Y is not 2}"
renderSql(sql, x = 0, y = 1)$sql
```

This produces:  "SELECT \* FROM table ; " But expected "Y is not 2"

Is this a bug or does each IF statement need to be completely self-contained with no innner-ifs?

-Chris

**Comment by schuemie** [comment]
`@y = 2` should be `@y == 2` and it will work fine.

This has also happened to me on several occasions. We could (a) also accept single `=` to mean comparison, or (b) let SqlRender throw an error if it encounters a single `=`. What do you think?

**Comment by chrisknoll** [comment]
On the fence: on one hand, = is assignment, == is comparison (and i should have noticed that in my test case, sorry).  Probably an error to the effect of "Assignment not valid in a conditional of if expression".

**Comment by hripcsa** [comment]
I agree with an error rather than a translation.

On May 30, 2016, at 2:27 AM, Chris Knoll <notifications@github.com<mailto:notifications@github.com>> wrote:


On the fence: on one hand, = is assignment, == is comparison (and i should have noticed that in my test case, sorry). Probably an error to the effect of "Assignment not valid in a conditional of if expression".
