### ISSUE TITLE
Remove sourceDialect argument

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#59]
This argument was deprecated (see https://github.com/OHDSI/SqlRender/issues/18 ). Should be removed completely after everyone has had time to adjust their code.

**Comment by alondhe** [comment]
This parameter reordering affects the FeatureExtraction package's GetDefaultCovariates function. It looks like its usage of TranslateSql doesn't explicitly assign parameters, but rather depends on the original parameter ordering. 

Example: 
` covariateSql <- SqlRender::translateSql(covariateSql,
                                          "sql server",
                                          attr(connection, "dbms"),
                                          oracleTempSchema)$sql`

The latest TranslateSql makes the targetDialect the 2nd parameter, and moves sourceDialect (to be deprecated) to the end. Instead, it should be:
`  covariateSql <- SqlRender::translateSql(sql = covariateSql,
                                          targetDialect = attr(connection, "dbms"),
                                          oracleTempSchema = oracleTempSchema)$sql`

I think across the board, we should use explicit parameters when making function calls rather than using the assumed ordering to avoid situations like this. I'll be submitting a PR for FeatureExtraction shortly, but just wanted to highlight this issue here first.

**Comment by chrisknoll** [comment]
> I think across the board, we should use explicit parameters when making function calls rather than using the assumed ordering to avoid situations like this. I'll be submitting a PR for FeatureExtraction shortly, but just wanted to highlight this issue here first.

I definitely agree with this: we've had problems on the Achilles package where as we added optional parameters over time, it messed with what people were expecting to be the default order.   Even adding optional params at the end wasn't bullet proof. So I agree with @alondhe , if a method signature uses optional params, be explicit in naming each parameter when calling it.

**Comment by schuemie** [comment]
Agreed. I've added this to [our code style guidelines](http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r#use_named_arguments)
